name: ctmanager
description: A helper capable of managing multiple cancellation tokens with ease. Useful for operations like http requests, image processing, etc, that can be cancelled by user.
version: 0.0.2
repository: https://github.com/iandis/ctmanager
issue_tracker: https://github.com/iandis/ctmanager/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.6.1
  meta: ^1.3.0

dev_dependencies:
  fake_async: ^1.2.0
  lint: ^1.6.0
  test: ^1.17.11