name: ctmanager
description: A helper capable of managing multiple cancellation tokens with ease. Useful for operations like http requests, image processing, etc, that can be cancelled by user.
version: 0.0.1+1
repository: https://github.com/iandis/ctmanager
issue_tracker: https://github.com/iandis/ctmanager/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.6.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
